version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: atm_postgres
    restart: always
    environment:
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: atm_password
      POSTGRES_DB: atm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: